// Code generated by go run ./hack/tsgen -types; DO NOT EDIT.

// The JSON of the daemon's answers and notices, and of the web process's own,
// as encoding/json writes the Go types. A field it may leave out is optional.
// A list Go left nil is null on the wire; the state sends [] instead.

// cfapi.Account
export interface Account {
  id: string
  name: string
}

// reconcile.Action
export interface Action {
  kind: string
  credentialId: string
  accountId?: string
  target: string
  detail: string
  destructive: boolean
  applied: boolean
  held?: string
}

// engine.AnnotationView
export interface AnnotationView {
  ref: string
  block: string
  startLine: number
  issues: Issue[]
}

// engine.ApplyResult
export interface ApplyResult {
  leftObserveOnly: boolean
  accepted: Waiting[]
}

// engine.Approval
export interface Approval {
  owner: string
  guest?: GuestView
  identity: string
  mode: string
  macs?: string[]
  addresses?: string[]
}

// engine.ApprovalView
export interface ApprovalView {
  owner: string
  guest?: GuestView
  identity: string
  current?: string
  matches: boolean
  macs?: string[]
  addresses?: string[]
}

// resolve.CandidateResult
export interface CandidateResult {
  addr: string
  source: string
  ok: boolean
  reason?: string
  level?: string
}

// credentials.Check
export interface Check {
  capability: string
  scope?: string
  scopeId?: string
  ok: boolean
  detail?: string
  unanswered?: boolean
}

// engine.ClaimView
export interface ClaimView {
  hostname: string
  holder: string
  guest?: GuestView
  since: string
  missingSince?: string
  state: string
  waiting: ClaimantView[]
}

// engine.ClaimantView
export interface ClaimantView {
  owner: string
  guest?: GuestView
  since: string
}

// reconcile.Conflict
export interface Conflict {
  zone: string
  name: string
  type: string
  content: string
}

// connector.Status
export interface ConnectorStatus {
  tunnelId: string
  active: boolean
  ready: boolean
  connections: number
  connectorId?: string
  metricsAddr?: string
  install?: string
  tokenRefused?: boolean
  metricsPortHeld?: boolean
}

// engine.CredentialView
export interface CredentialView {
  id: string
  label: string
  kind: string
  checked: boolean
  report?: Report
}

// wire.DoctorCounts
export interface DoctorCounts {
  ok: number
  warn: number
  fail: number
  at: string
}

// connector.Edge
export interface Edge {
  connection: number
  location: string
}

// engine.EgressView
export interface EgressView {
  state: string
  since?: string
}

// api.ErrorBody
export interface ErrorBody {
  error: string
  code: string
  field?: string
  credential?: unknown
}

// engine.Event
export interface Event {
  seq: number
  boot?: string
  at?: string
  level: string
  kind: string
  subject: string
  message: string
  route?: string
  guest?: string
  tunnel?: string
  account?: string
  actor?: string
}

// credentials.Exclusion
export interface Exclusion {
  zone: string
  zoneId: string
  reason: string
  detail: string
}

// doctor.Finding
export interface Finding {
  check: string
  level: string
  detail: string
  fix?: string
}

// engine.GapNotice
export interface GapNotice {
  boot: string
  from: number
  to: number
  count: number
  level: string
}

// engine.GuestListView
export interface GuestListView {
  ref: string
  name?: string
  node: string
  running: boolean
  tagged: boolean
  identity?: string
  approval: string
  routes: number
  issues: number
}

// model.GuestRef
export interface GuestRef {
  kind: string
  vmid: number
}

// engine.GuestView
export interface GuestView {
  kind: string
  vmid: number
  name?: string
}

// engine.Hello
export interface Hello {
  boot: string
  version: string
  seq: number
  digest: string
  pollInterval: string
}

// engine.IdentityView
export interface IdentityView {
  vmid: number
  node: string
  ok: boolean
  why?: string
  copy: boolean
  copies?: string[]
  tenants?: string[]
  exposed?: string[]
  checkedAt?: string
}

// planner.IngressRule
export interface IngressRule {
  hostname?: string
  service: string
  originServerName?: string
  matchSNItoHost?: boolean
  noTLSVerify?: boolean
  httpHostHeader?: string
}

// planner.Issue
export interface Issue {
  guest?: GuestRef
  line?: number
  col?: number
  msg: string
}

// engine.Limit
export interface Limit {
  min?: unknown
  max?: unknown
}

// engine.ManualRouteView
export interface ManualRouteView {
  id: string
  rev: number
  hostname: string
  target: ManualTarget
  options: RouteOptions
}

// engine.ManualTarget
export interface ManualTarget {
  kind: string
  guest?: string
  scheme: string
  addr?: string
  port: number
}

// engine.PathView
export interface PathView {
  node: string
  bridge?: string
  vlan?: number
  port?: string
  mac?: string
  verifiedAt: string
  since?: string
}

// credentials.Report
export interface Report {
  token: TokenStatus
  accounts: Account[]
  zones: Zone[]
  checks: Check[]
  excluded: Exclusion[]
  deep: boolean
  usable: boolean
  leftovers: string[]
  checkedAt?: string
}

// engine.RogueConnector
export interface RogueConnector {
  tunnel: string
  tunnelId: string
  accountId: string
  id: string
  originIp?: string
  version?: string
  since: string
}

// engine.RolloutView
export interface RolloutView {
  version: number
  connectors: number
  confirmedAt: string
}

// model.RouteOptions
export interface RouteOptions {
  noTLSVerify?: boolean
  hostHeader?: string
  sni?: string
  via?: string
  allowNode?: boolean
}

// engine.RouteSample
export interface RouteSample {
  at: string
  flowsPerSec: number
}

// engine.RouteSeries
export interface RouteSeries {
  hostname: string
  target: string
  shared: number
  samples: RouteSample[]
}

// engine.RouteTraffic
export interface RouteTraffic {
  hostname: string
  owner: string
  target: string
  flowsPerSec: number
  shared?: number
  stale: boolean
}

// engine.RouteView
export interface RouteView {
  hostname: string
  owner: string
  state: string
  level?: string
  reason?: string
  service?: string
  zone?: string
  warnings?: string[]
  guest?: GuestView
  candidates?: CandidateResult[]
  accountId?: string
  rule?: IngressRule
  path?: PathView
}

// engine.SegmentView
export interface SegmentView {
  bridge: string
  vlan?: number
  acknowledged: boolean
  acknowledgedAt?: string
  routes: number
}

// wire.Session
export interface Session {
  user: string
  method: string
  role: string
  csrf: string
  idleExpiresAt: string
  expiresAt: string
  profile: string
  node: string
  nodeZone: string
  version: string
}

// store.Settings
export interface Settings {
  gateTag: string
  allowHosts?: string[]
  denyHosts?: string[]
  pollInterval: string
  grace: string
  trustStatic?: boolean
  trustedCIDRs?: string[]
  manualCIDRs?: string[]
  admission: string
  zonePins?: Record<string, string>
  observeOnly: boolean
  identityMinimum: string
  maxHostnamesPerGuest: number
  reverifyInterval: string
  cloudflareBudget: number
}

// engine.SettingsView
export interface SettingsView {
  rev: number
  settings: Settings
  readAtStart: string[]
  limits: Record<string, Limit>
  notes: string[]
}

// engine.State
export interface State {
  at?: string
  finishedAt?: string
  node?: string
  digest?: string
  mode: string
  complete: boolean
  routes: RouteView[]
  issues: Issue[]
  tunnels: TunnelView[]
  connectors: ConnectorStatus[]
  credentials: CredentialView[]
  zones: ZoneView[]
  actions: Action[]
  conflicts: Conflict[]
  lost: string[]
  problems: string[]
  writerVerdict: string
  hold?: string
  profile?: string
  waiting: Waiting[]
  offer?: string
  unapproved: UnapprovedGuest[]
  segments: SegmentView[]
  egress?: EgressView
  admission?: string
  gateTagged: number
  rogueConnectors: RogueConnector[]
  identity?: IdentityView
  epochDrawnAt?: string
}

// engine.StateNotice
export interface StateNotice {
  at: string
  finishedAt: string
  digest: string
}

// doctor.Step
export interface Step {
  name: string
  level: string
  detail: string
  skipped?: boolean
}

// cfapi.TokenStatus
export interface TokenStatus {
  id: string
  status: string
  expiresOn?: string
}

// engine.TrafficNotice
export interface TrafficNotice {
  at: string
  tunnels: TunnelNotice[]
  routes?: RouteTraffic[]
  routesTotal: number
  routesWhy?: string
}

// engine.TrafficSample
export interface TrafficSample {
  at: string
  rps: number
  errorsPerSec: number
  concurrent: number
}

// engine.TrafficView
export interface TrafficView {
  at: string
  interval: string
  tunnels: TunnelTraffic[]
  routes: RouteTraffic[]
  routesTotal: number
  routesWhy?: string
}

// engine.TunnelNotice
export interface TunnelNotice {
  tunnelId: string
  rps: number
  errorsPerSec: number
  concurrent: number
  haConnections: number
  stale: boolean
  sampled?: boolean
}

// engine.TunnelTraffic
export interface TunnelTraffic {
  tunnelId: string
  node: string
  cloudflared?: string
  configVersion: number
  haConnections: number
  edges: Edge[]
  rttMs: number[]
  stale: boolean
  samples: TrafficSample[]
}

// engine.TunnelView
export interface TunnelView {
  accountId: string
  credentialId: string
  name: string
  id?: string
  version: number
  exists: boolean
  verified: boolean
  unknown: boolean
  held?: string
  leftAsIs?: boolean
  unchecked: boolean
  rollout?: RolloutView
}

// engine.UnapprovedGuest
export interface UnapprovedGuest {
  kind: string
  vmid: number
  name?: string
  identity?: string
  hostnames: string[]
  why: string[]
  macs?: string[]
  addresses?: string[]
}

// wire.Unauthenticated
export interface Unauthenticated {
  code: string
  methods: string[]
  ticket: boolean
  realms?: string[]
}

// wire.Upstream
export interface Upstream {
  up: boolean
  since: string
}

// api.Version
export interface Version {
  version: string
  boot: string
  profile: string
  node: string
  pollInterval: string
}

// engine.Waiting
export interface Waiting {
  kind: string
  subject: string
  detail: string
  items: string[]
}

// wire.Error
export interface WebError {
  error: string
  code: string
  field?: string
  missing?: string
  retryAfter?: number
}

// cfapi.Zone
export interface Zone {
  id: string
  name: string
  status: string
  accountId: string
}

// engine.ZoneView
export interface ZoneView {
  name: string
  id: string
  status: string
  accountId: string
  state: string
  credentials: string[]
  servedBy?: string
  pinned?: string
  stale: string[]
  excluded: string[]
  frozenWhy?: string
}

// The JSON names of the fields of engine.State, in their order; app/fields.ts
// says where the page shows each.
export const stateFields: readonly string[] = [
  "at",
  "finishedAt",
  "node",
  "digest",
  "mode",
  "complete",
  "routes",
  "issues",
  "tunnels",
  "connectors",
  "credentials",
  "zones",
  "actions",
  "conflicts",
  "lost",
  "problems",
  "writerVerdict",
  "hold",
  "profile",
  "waiting",
  "offer",
  "unapproved",
  "segments",
  "egress",
  "admission",
  "gateTagged",
  "rogueConnectors",
  "identity",
  "epochDrawnAt",
]
