// Code generated by go run ./hack/tsgen -words; DO NOT EDIT.

// The words of internal/present that are lookups, and the classes of
// characters present.Printable replaces. The functions with logic are written
// again in TypeScript; both are checked against the cases of
// internal/present/testdata/words.json.

// present.EgressText, by the state of the egress filter; another state is shown
// as it is.
export const egressWords: Readonly<Record<string, string>> = {
  "": "not checked yet",
  "changed": "not the one pco loads: the connectors may not be confined",
  "not loaded": "not loaded: the connectors are not confined",
  "off": "off: the connectors are not confined",
  "on": "on",
}

// present.WriterText, by the verdict on the writer; another verdict is shown as
// it is.
export const writerWords: Readonly<Record<string, string>> = {
  "": "-",
  "foreign": "foreign (another installation is writing)",
  "ok": "ok",
  "stale": "stale (a newer generation of this install is writing)",
  "unknown": "unknown (leader.json could not be used)",
}

// The words of present.VerifiedText, in the order it looks at the tunnel.
export const verifiedWords = {
  unchecked: "unchecked",
  held: "held",
  unknown: "unknown",
  verified: "yes",
  unverified: "no",
} as const

// present.RouteStateOrder: the order routes are counted in; a state that is not
// listed follows, by name.
export const routeStateOrder: readonly string[] = [
  "active",
  "unreachable",
  "withdrawn",
  "conflict",
  "no-zone",
  "held",
  "rejected",
  "frozen",
]

// The forms of the values a command for a root shell may carry, by kind, as
// present.CommandArg checks them.
export const argForms: Readonly<Record<string, string>> = {
  "account id": "^[0-9a-f]{32}$",
  "hostname": "^([a-z0-9-]{1,63}\\.)+[a-z0-9-]{2,63}$",
  "owner": "^(qemu|lxc)/[0-9]+$",
}

// The words of the line that says what waits for Cloudflare's rate limit, which
// present.BudgetWait reads: its end, after the verb, and the beginnings of the
// reads that wait.
export const rateLimitWait = "for Cloudflare's rate limit"
export const waitingReads: readonly string[] = [
  "the listing of zone ",
  "the tunnel of account ",
]

// Printable replaces the controls of C0 and C1, with DEL (unicode.Cc): sorted
// ranges of code points, both ends included.
export const controlRanges: readonly (readonly [number, number])[] = [
  [0x0000, 0x001f],
  [0x007f, 0x009f],
]

// Printable replaces the characters of format (unicode.Cf): sorted ranges of
// code points, both ends included.
export const formatRanges: readonly (readonly [number, number])[] = [
  [0x00ad, 0x00ad],
  [0x0600, 0x0605],
  [0x061c, 0x061c],
  [0x06dd, 0x06dd],
  [0x070f, 0x070f],
  [0x0890, 0x0891],
  [0x08e2, 0x08e2],
  [0x180e, 0x180e],
  [0x200b, 0x200f],
  [0x202a, 0x202e],
  [0x2060, 0x2064],
  [0x2066, 0x206f],
  [0xfeff, 0xfeff],
  [0xfff9, 0xfffb],
  [0x110bd, 0x110bd],
  [0x110cd, 0x110cd],
  [0x13430, 0x1343f],
  [0x1bca0, 0x1bca3],
  [0x1d173, 0x1d17a],
  [0xe0001, 0xe0001],
  [0xe0020, 0xe007f],
]

// Printable replaces the controls of direction and the separators of lines
// (present.IsBidi): sorted ranges of code points, both ends included.
export const bidiRanges: readonly (readonly [number, number])[] = [
  [0x061c, 0x061c],
  [0x200e, 0x200f],
  [0x2028, 0x202e],
  [0x2066, 0x2069],
]
