package egress

import (
	"net/netip"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestResolversAreTheNameServersOfResolvConf(t *testing.T) {
	path := filepath.Join(t.TempDir(), "resolv.conf")
	require.NoError(t, os.WriteFile(path, []byte(strings.Join([]string{
		"# Generated by the installer",
		"search example.com",
		"nameserver 192.168.1.1",
		"  nameserver\t10.0.0.53   # trailing words are ignored",
		"nameserver fe80::1%vmbr0",
		"nameserver ::ffff:10.0.0.54",
		"nameserver not-an-address",
		"nameserver",
		";nameserver 10.9.9.9",
		"#nameserver 10.9.9.8",
		"options edns0",
		"nameserver 127.0.0.53",
		"nameserver 192.168.1.2",
	}, "\n")+"\n"), 0o644))

	got, err := readResolvers(path)

	require.NoError(t, err)
	require.Equal(t, []netip.Addr{
		addr("192.168.1.1"), addr("10.0.0.53"), addr("fe80::1"), addr("10.0.0.54"),
		addr("127.0.0.53"), addr("192.168.1.2"),
	}, got, "every valid one the file holds and nothing else, zones and IPv4 mapping taken off")
}

func TestNoResolvConfMeansNoResolvers(t *testing.T) {
	got, err := readResolvers(filepath.Join(t.TempDir(), "resolv.conf"))

	require.NoError(t, err)
	require.Empty(t, got)
}

func TestAResolvConfThatCannotBeReadIsAnError(t *testing.T) {
	_, err := readResolvers(t.TempDir())

	require.Error(t, err)
}

func TestTheLineCutOffByTheSizeLimitIsNotRead(t *testing.T) {
	path := filepath.Join(t.TempDir(), "resolv.conf")
	head := "nameserver 192.168.1.1\n"
	filler := "#" + strings.Repeat("x", maxResolvConf-len(head)-len("nameserver 10.0.0.1")-2) + "\n"
	// The limit falls inside 10.0.0.12, which must not be read as 10.0.0.1.
	require.NoError(t, os.WriteFile(path, []byte(head+filler+"nameserver 10.0.0.12\n"), 0o644))

	got, err := readResolvers(path)

	require.NoError(t, err)
	require.Equal(t, []netip.Addr{addr("192.168.1.1")}, got)
}
