package main

import (
	"encoding"
	"encoding/json"
	"fmt"
	"maps"
	"reflect"
	"slices"
	"strings"

	"github.com/anaryk/proxmox-cloudflared-operator/internal/api"
	"github.com/anaryk/proxmox-cloudflared-operator/internal/connector"
	"github.com/anaryk/proxmox-cloudflared-operator/internal/doctor"
	"github.com/anaryk/proxmox-cloudflared-operator/internal/engine"
	"github.com/anaryk/proxmox-cloudflared-operator/internal/web/wire"
)

const typesHeader = `// Code generated by go run ./hack/tsgen -types; DO NOT EDIT.

// The JSON of the daemon's answers and notices, and of the web process's own,
// as encoding/json writes the Go types. A field it may leave out is optional.
// A list Go left nil is null on the wire; the state sends [] instead.
`

// typeRoots are the types the interface reads, each with the types its fields
// hold.
func typeRoots() []reflect.Type {
	return []reflect.Type{
		reflect.TypeFor[engine.State](),
		reflect.TypeFor[engine.ZoneView](),
		reflect.TypeFor[engine.PathView](),
		reflect.TypeFor[engine.RolloutView](),
		reflect.TypeFor[engine.Event](),
		reflect.TypeFor[engine.Hello](),
		reflect.TypeFor[engine.StateNotice](),
		reflect.TypeFor[engine.GapNotice](),
		reflect.TypeFor[engine.TrafficView](),
		reflect.TypeFor[engine.TrafficNotice](),
		reflect.TypeFor[engine.RouteTraffic](),
		reflect.TypeFor[engine.RouteSeries](),
		reflect.TypeFor[engine.ApplyResult](),
		reflect.TypeFor[engine.Waiting](),
		reflect.TypeFor[engine.CredentialView](),
		reflect.TypeFor[engine.ClaimView](),
		reflect.TypeFor[engine.ApprovalView](),
		reflect.TypeFor[engine.Approval](),
		reflect.TypeFor[engine.SettingsView](),
		reflect.TypeFor[engine.ManualRouteView](),
		reflect.TypeFor[engine.GuestListView](),
		reflect.TypeFor[engine.AnnotationView](),
		reflect.TypeFor[doctor.Step](),
		reflect.TypeFor[doctor.Finding](),
		reflect.TypeFor[api.ErrorBody](),
		reflect.TypeFor[api.Version](),
		reflect.TypeFor[wire.Session](),
		reflect.TypeFor[wire.Unauthenticated](),
		reflect.TypeFor[wire.Error](),
		reflect.TypeFor[wire.DoctorCounts](),
		reflect.TypeFor[wire.Upstream](),
	}
}

// renamed are the types whose Go name is taken in TypeScript, or by another
// type of the list.
var renamed = map[reflect.Type]string{
	reflect.TypeFor[wire.Error]():       "WebError", // Error is the global class
	reflect.TypeFor[connector.Status](): "ConnectorStatus",
}

var (
	textMarshaler = reflect.TypeFor[encoding.TextMarshaler]()
	jsonMarshaler = reflect.TypeFor[json.Marshaler]()
	rawMessage    = reflect.TypeFor[json.RawMessage]()
)

// marshalsTo names what the types that write their own JSON write: a type
// not listed here fails the generator, rather than being guessed at.
var marshalsTo = map[string]string{
	"github.com/anaryk/proxmox-cloudflared-operator/internal/store.Secret": "string",
}

// field is a field of an interface.
type field struct {
	name     string
	ts       string
	optional bool
}

// declaration is an interface the module declares.
type declaration struct {
	name   string
	origin string // the Go type, as package.Name
	fields []field
}

type typeWriter struct {
	decls map[string]*declaration
	names map[reflect.Type]string
}

// typesModule is the TypeScript module of the types, and the JSON names of the
// fields of engine.State, which every page has to give a home.
func typesModule() (string, error) {
	w := &typeWriter{decls: make(map[string]*declaration), names: make(map[reflect.Type]string)}
	for _, t := range typeRoots() {
		if _, err := w.named(t); err != nil {
			return "", err
		}
	}
	var b strings.Builder
	b.WriteString(typesHeader)
	for _, name := range slices.Sorted(maps.Keys(w.decls)) {
		d := w.decls[name]
		fmt.Fprintf(&b, "\n// %s\nexport interface %s {\n", d.origin, d.name)
		for _, f := range d.fields {
			opt := ""
			if f.optional {
				opt = "?"
			}
			fmt.Fprintf(&b, "  %s%s: %s\n", f.name, opt, f.ts)
		}
		b.WriteString("}\n")
	}

	state, err := w.fields(reflect.TypeFor[engine.State]())
	if err != nil {
		return "", err
	}
	names := make([]string, len(state))
	for i, f := range state {
		names[i] = f.name
	}
	section(&b, "The JSON names of the fields of engine.State, in their order; app/fields.ts says where the page shows each.")
	list(&b, "stateFields", names)
	return b.String(), nil
}

// named declares the struct t, once, and returns its name.
func (w *typeWriter) named(t reflect.Type) (string, error) {
	if name, ok := w.names[t]; ok {
		return name, nil
	}
	name := t.Name()
	if n, ok := renamed[t]; ok {
		name = n
	}
	if d, ok := w.decls[name]; ok {
		return "", fmt.Errorf("%s and %s are both %s in TypeScript: rename one in renamed", d.origin, origin(t), name)
	}
	d := &declaration{name: name, origin: origin(t)}
	w.decls[name] = d
	w.names[t] = name
	fields, err := w.fields(t)
	if err != nil {
		return "", err
	}
	d.fields = fields
	return name, nil
}

func origin(t reflect.Type) string {
	pkg := t.PkgPath()
	return pkg[strings.LastIndex(pkg, "/")+1:] + "." + t.Name()
}

// fields are the fields of the struct t as encoding/json writes them: those
// of an embedded struct without a name of its own in its place, unless a
// field less deep has the same name. Of two as deep, a tagged one wins, and
// with no such one neither is written.
func (w *typeWriter) fields(t reflect.Type) ([]field, error) {
	type candidate struct {
		f      reflect.StructField
		name   string
		opts   string
		depth  int
		tagged bool
	}
	var all []candidate
	var walk func(t reflect.Type, depth int) error
	walk = func(t reflect.Type, depth int) error {
		for i := range t.NumField() {
			f := t.Field(i)
			tag := f.Tag.Get("json")
			if tag == "-" {
				continue
			}
			name, opts, _ := strings.Cut(tag, ",")
			if f.Anonymous && name == "" {
				if f.Type.Kind() == reflect.Pointer {
					return fmt.Errorf("%s embeds the pointer %s, which the generator does not take", origin(t), f.Type)
				}
				if f.Type.Kind() == reflect.Struct && !writesItself(f.Type) {
					if err := walk(f.Type, depth+1); err != nil {
						return err
					}
					continue
				}
			}
			if !f.IsExported() {
				continue
			}
			tagged := name != ""
			if !tagged {
				name = f.Name
			}
			all = append(all, candidate{f: f, name: name, opts: opts, depth: depth, tagged: tagged})
		}
		return nil
	}
	if err := walk(t, 0); err != nil {
		return nil, err
	}

	var out []field
	for _, c := range all {
		var rivals []candidate
		for _, o := range all {
			if o.name == c.name && o.depth == c.depth && o.tagged == c.tagged {
				rivals = append(rivals, o)
			}
		}
		won := !slices.ContainsFunc(all, func(o candidate) bool {
			return o.name == c.name && (o.depth < c.depth || o.depth == c.depth && o.tagged && !c.tagged)
		})
		if !won || len(rivals) > 1 {
			continue
		}
		ts, err := w.tsType(c.f.Type)
		if err != nil {
			return nil, fmt.Errorf("%s.%s: %w", origin(t), c.f.Name, err)
		}
		optional := omitted(c.f.Type, c.opts)
		if c.f.Type.Kind() == reflect.Pointer && !optional {
			ts += " | null"
		}
		if hasOption(c.opts, "string") {
			ts = "string"
		}
		out = append(out, field{name: c.name, ts: ts, optional: optional})
	}
	return out, nil
}

// omitted says whether encoding/json may leave a field of type t out with
// the options of its tag: omitzero always may; omitempty never leaves out a
// struct.
func omitted(t reflect.Type, opts string) bool {
	if hasOption(opts, "omitzero") {
		return true
	}
	if !hasOption(opts, "omitempty") {
		return false
	}
	return t.Kind() != reflect.Struct && (t.Kind() != reflect.Array || t.Len() == 0)
}

func hasOption(opts, want string) bool {
	for o := range strings.SplitSeq(opts, ",") {
		if o == want {
			return true
		}
	}
	return false
}

func writesItself(t reflect.Type) bool {
	return t.Implements(textMarshaler) || reflect.PointerTo(t).Implements(textMarshaler) ||
		t.Implements(jsonMarshaler) || reflect.PointerTo(t).Implements(jsonMarshaler)
}

// tsType is the TypeScript of a value of type t.
func (w *typeWriter) tsType(t reflect.Type) (string, error) {
	switch {
	case t == rawMessage:
		return "unknown", nil
	case t.Implements(textMarshaler) || reflect.PointerTo(t).Implements(textMarshaler):
		// time.Time, netip.Addr, netip.Prefix, durations and levels
		return "string", nil
	case t.Implements(jsonMarshaler) || reflect.PointerTo(t).Implements(jsonMarshaler):
		ts, ok := marshalsTo[t.PkgPath()+"."+t.Name()]
		if !ok {
			return "", fmt.Errorf("%s writes its own JSON: say what in marshalsTo", t)
		}
		return ts, nil
	}
	switch t.Kind() {
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", nil
	case reflect.String:
		return "string", nil
	case reflect.Interface:
		return "unknown", nil
	case reflect.Pointer:
		return w.tsType(t.Elem())
	case reflect.Slice, reflect.Array:
		if t.Elem().Kind() == reflect.Uint8 && t.Kind() == reflect.Slice {
			return "string", nil // base64
		}
		elem, err := w.tsType(t.Elem())
		if err != nil {
			return "", err
		}
		if strings.Contains(elem, " ") {
			elem = "(" + elem + ")"
		}
		return elem + "[]", nil
	case reflect.Map:
		if t.Key().Kind() != reflect.String {
			return "", fmt.Errorf("a map with keys of %s", t.Key())
		}
		elem, err := w.tsType(t.Elem())
		if err != nil {
			return "", err
		}
		return "Record<string, " + elem + ">", nil
	case reflect.Struct:
		return w.named(t)
	}
	return "", fmt.Errorf("no TypeScript for %s", t)
}
