package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"maps"
	"slices"
	"strings"
	"unicode"

	"github.com/anaryk/proxmox-cloudflared-operator/internal/engine"
	"github.com/anaryk/proxmox-cloudflared-operator/internal/present"
	"github.com/anaryk/proxmox-cloudflared-operator/internal/reconcile"
)

const wordsHeader = `// Code generated by go run ./hack/tsgen -words; DO NOT EDIT.

// The words of internal/present that are lookups, and the classes of
// characters present.Printable replaces. The functions with logic are written
// again in TypeScript; both are checked against the cases of
// internal/present/testdata/words.json.
`

// class is a class of characters that present.Printable replaces.
type class struct {
	name, doc string
	in        func(rune) bool
}

func printableClasses() []class {
	return []class{
		{"controlRanges", "the controls of C0 and C1, with DEL (unicode.Cc)", unicode.IsControl},
		{"formatRanges", "the characters of format (unicode.Cf)", func(r rune) bool { return unicode.Is(unicode.Cf, r) }},
		{"bidiRanges", "the controls of direction and the separators of lines (present.IsBidi)", present.IsBidi},
	}
}

// wordsModule is the TypeScript module of the words. Each table is what the
// function of internal/present returns for the keys, so the two cannot say
// different things.
func wordsModule() string {
	var b strings.Builder
	b.WriteString(wordsHeader)

	egress := make(map[string]string)
	for _, s := range []string{"", engine.EgressOn, engine.EgressOff, engine.EgressNotLoaded, engine.EgressChanged} {
		egress[s] = present.EgressText(engine.EgressView{State: s})
	}
	section(&b, "present.EgressText, by the state of the egress filter; another state is shown as it is.")
	record(&b, "egressWords", egress)

	writer := make(map[string]string)
	for _, v := range []string{"", engine.VerdictOK, engine.VerdictStale, engine.VerdictForeign, engine.VerdictUnknown} {
		writer[v] = present.WriterText(v)
	}
	section(&b, "present.WriterText, by the verdict on the writer; another verdict is shown as it is.")
	record(&b, "writerWords", writer)

	section(&b, "The words of present.VerifiedText, in the order it looks at the tunnel.")
	object(&b, "verifiedWords", [][2]string{
		{"unchecked", present.VerifiedText(engine.TunnelView{Unchecked: true})},
		{"held", present.VerifiedText(engine.TunnelView{Held: "held"})},
		{"unknown", present.VerifiedText(engine.TunnelView{TunnelState: reconcile.TunnelState{Unknown: true}})},
		{"verified", present.VerifiedText(engine.TunnelView{TunnelState: reconcile.TunnelState{Verified: true}})},
		{"unverified", present.VerifiedText(engine.TunnelView{})},
	})

	order := make([]string, len(present.RouteStateOrder))
	for i, s := range present.RouteStateOrder {
		order[i] = string(s)
	}
	section(&b, "present.RouteStateOrder: the order routes are counted in; a state that is not listed follows, by name.")
	list(&b, "routeStateOrder", order)

	forms := make(map[string]string)
	for _, kind := range []string{present.ArgAccount, present.ArgOwner, present.ArgHostname} {
		forms[kind] = present.ArgForm(kind)
	}
	section(&b, "The forms of the values a command for a root shell may carry, by kind, as present.CommandArg checks them.")
	record(&b, "argForms", forms)

	section(&b, "The words of the line that says what waits for Cloudflare's rate limit, which present.BudgetWait reads: its end, after the verb, and the beginnings of the reads that wait.")
	fmt.Fprintf(&b, "export const rateLimitWait = %s\n", quote(reconcile.RateLimitWait))
	list(&b, "waitingReads", []string{reconcile.ZoneListingRead, reconcile.TunnelRead})

	for _, c := range printableClasses() {
		section(&b, "Printable replaces "+c.doc+": sorted ranges of code points, both ends included.")
		fmt.Fprintf(&b, "export const %s: readonly (readonly [number, number])[] = [\n", c.name)
		for _, r := range ranges(c.in) {
			fmt.Fprintf(&b, "  [0x%04x, 0x%04x],\n", r[0], r[1])
		}
		b.WriteString("]\n")
	}
	return b.String()
}

// ranges are the code points in a class, as sorted ranges that neither
// overlap nor touch.
func ranges(in func(rune) bool) [][2]rune {
	var out [][2]rune
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if !in(r) {
			continue
		}
		if n := len(out); n > 0 && out[n-1][1] == r-1 {
			out[n-1][1] = r
		} else {
			out = append(out, [2]rune{r, r})
		}
	}
	return out
}

// section begins a declaration with its comment, wrapped at 80 columns.
func section(b *strings.Builder, doc string) {
	b.WriteString("\n")
	line := "//"
	for _, word := range strings.Fields(doc) {
		if len(line)+1+len(word) > 80 {
			b.WriteString(line + "\n")
			line = "//"
		}
		line += " " + word
	}
	b.WriteString(line + "\n")
}

func record(b *strings.Builder, name string, m map[string]string) {
	fmt.Fprintf(b, "export const %s: Readonly<Record<string, string>> = {\n", name)
	for _, k := range slices.Sorted(maps.Keys(m)) {
		fmt.Fprintf(b, "  %s: %s,\n", quote(k), quote(m[k]))
	}
	b.WriteString("}\n")
}

func object(b *strings.Builder, name string, fields [][2]string) {
	fmt.Fprintf(b, "export const %s = {\n", name)
	for _, f := range fields {
		fmt.Fprintf(b, "  %s: %s,\n", f[0], quote(f[1]))
	}
	b.WriteString("} as const\n")
}

func list(b *strings.Builder, name string, items []string) {
	fmt.Fprintf(b, "export const %s: readonly string[] = [\n", name)
	for _, it := range items {
		fmt.Fprintf(b, "  %s,\n", quote(it))
	}
	b.WriteString("]\n")
}

// quote writes a string as JSON, which is a string of JavaScript too.
func quote(s string) string {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	_ = enc.Encode(s)
	return strings.TrimSuffix(buf.String(), "\n")
}
